name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: alpine-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: make docker-build

    - uses: docker/scout-action@v1.12.0
      with:
        command: docker scout quickview


          
